qqmusic::utils::SessionManager
std::mutex qqmusic::utils::SessionManager::lock
对全局上下文负责的互斥锁
qqmusic::details::NetworkContext qqmusic::utils::SessionManager::ctx
全局上下文实例, 即上下文栈的栈顶
std::stack<qqmusic::details::NetworkContext> qqmusic::utils::SessionManager::context_stack
全局上下文栈
std::shared_ptr<asio::io_context> qqmusic::utils::SessionManager::ioc
std::shared_ptr<asio::ssl::context> qqmusic::utils::SessionManager::ssl_ctx
qqmusic::utils::SessionManager::SessionManager(const SessionManager &)=delete
SessionManager qqmusic::utils::SessionManager::operator=(const SessionManager &)=delete
Session qqmusic::utils::SessionManager::get_session()
获取一个session实例
Referenced by qqmusic::get_album_list, qqmusic::get_fav_num, qqmusic::get_labels, qqmusic::get_mv_list, qqmusic::get_other_version, qqmusic::get_other_version, qqmusic::get_producer_info, qqmusic::get_producer_info, qqmusic::get_related_mv, qqmusic::get_related_songlist, qqmusic::get_sheet, qqmusic::get_similar_singers, qqmusic::get_similar_songs, qqmusic::get_singer_desc, qqmusic::get_singer_info, qqmusic::get_singer_list, qqmusic::get_singer_list_index, qqmusic::get_song_detail, qqmusic::get_song_detail, qqmusic::get_song_urls, qqmusic::get_songs_list, qqmusic::get_tab_detail, qqmusic::get_toplist_category, qqmusic::get_toplist_item_detail, qqmusic::get_try_url, qqmusic::utils::Credential::is_expired, qqmusic::query_song, qqmusic::query_song, qqmusic::utils::Credential::refresh.
void qqmusic::utils::SessionManager::set_context(const qqmusic::details::NetworkContext &context)
替换上下文栈栈顶的上下文
void qqmusic::utils::SessionManager::push_context(qqmusic::details::NetworkContext &&context)
将指定的上下文压栈
void qqmusic::utils::SessionManager::pop_context()
上下文栈弹出栈顶元素
SessionManager & qqmusic::utils::SessionManager::get_instance()
获取Session管理器实例
Referenced by qqmusic::get_album_list, qqmusic::get_fav_num, qqmusic::get_labels, qqmusic::get_mv_list, qqmusic::get_other_version, qqmusic::get_other_version, qqmusic::get_producer_info, qqmusic::get_producer_info, qqmusic::get_related_mv, qqmusic::get_related_songlist, qqmusic::get_sheet, qqmusic::get_similar_singers, qqmusic::get_similar_songs, qqmusic::get_singer_desc, qqmusic::get_singer_info, qqmusic::get_singer_list, qqmusic::get_singer_list_index, qqmusic::get_song_detail, qqmusic::get_song_detail, qqmusic::get_song_urls, qqmusic::get_songs_list, qqmusic::get_tab_detail, qqmusic::get_toplist_category, qqmusic::get_toplist_item_detail, qqmusic::get_try_url, qqmusic::utils::Credential::is_expired, qqmusic::query_song, qqmusic::query_song, qqmusic::utils::Credential::refresh.
qqmusic::utils::SessionManager::SessionManager()