qqmusic::utils::PathManager
fs::path qqmusic::utils::PathManager::cache_path
fs::path qqmusic::utils::PathManager::log_path
fs::path qqmusic::utils::PathManager::download_path
PathManager & qqmusic::utils::PathManager::get_instance()
获取实例引用
Referenced by qqmusic::utils::cache_device, qqmusic::utils::get_device_info.
void qqmusic::utils::PathManager::set_download_path(std::string_view path)
设置下载路径
void qqmusic::utils::PathManager::set_download_path(const fs::path &path)
void qqmusic::utils::PathManager::set_cache_path(std::string_view path)
设置缓存路径
void qqmusic::utils::PathManager::set_cache_path(const fs::path &path)
void qqmusic::utils::PathManager::set_log_path(std::string_view path)
设置日志路径
void qqmusic::utils::PathManager::set_log_path(const fs::path &path)
std::filesystem::path qqmusic::utils::PathManager::get_cache_path() const
获取缓存路径
Referenced by qqmusic::utils::cache_device, qqmusic::utils::get_device_info.
std::filesystem::path qqmusic::utils::PathManager::get_download_path() const
获取下载路径
std::filesystem::path qqmusic::utils::PathManager::get_log_path() const
获取日志路径
qqmusic::utils::PathManager::PathManager()