qqmusic::utils
qrc_type
using qqmusic::utils::HttpResponse = typedef http::response<http::dynamic_body>
buffer qqmusic::utils::resp2buf(http::response< http::dynamic_body > &&resp)
将请求回复报文体转换成二进制buffer
resp 回复报文 qqmusic::utils::buffer类型buffer
Referenced by qqmusic::get_album_list, qqmusic::get_fav_num, qqmusic::get_labels, qqmusic::get_mv_list, qqmusic::get_other_version, qqmusic::get_other_version, qqmusic::get_producer_info, qqmusic::get_producer_info, qqmusic::get_related_mv, qqmusic::get_related_songlist, qqmusic::get_sheet, qqmusic::get_similar_singers, qqmusic::get_similar_songs, qqmusic::get_singer_desc, qqmusic::get_singer_info, qqmusic::get_singer_list, qqmusic::get_singer_list_index, qqmusic::get_song_detail, qqmusic::get_song_detail, qqmusic::get_song_urls, qqmusic::get_songs_list, qqmusic::get_tab_detail, qqmusic::get_toplist_category, qqmusic::get_toplist_item_detail, qqmusic::get_try_url, qqmusic::utils::Credential::is_expired, qqmusic::query_song, qqmusic::query_song, qqmusic::utils::Credential::refresh.
buffer qqmusic::utils::hex2buf(std::string_view hex)
十六进制字符串转成buffer
hex 十六进制编码字符串 qqmusic::utils::buffer类型buffer
static std::string qqmusic::utils::head(std::span< uint8_t > data)
static std::string qqmusic::utils::tail(std::span< uint8_t > data)
static std::string qqmusic::utils::middle(std::span< uint8_t > data)
std::string qqmusic::utils::sign(const nlohmann::json &params)
QQ音乐请求签名
params 请求数据表单 签名结果
Referenced by qqmusic::details::Api::prepare_request.
static int qqmusic::utils::decompress(const buffer &src, buffer &dest)
static void qqmusic::utils::qmc1_decrypt(buffer &src)
qqmusic::Result< std::string > qqmusic::utils::qrc_decode(const qqmusic::utils::buffer &src, qqmusic::utils::qrc_type type)
解码加密的QRC歌词
src 被加密的歌词 type 歌词类型 解码后的字符串, 如果出错会返回Exception
uint64_t qqmusic::utils::hash33(std::string_view str, uint64_t prev=0)
计算utf-8字符串的哈希值
str 待求值字符串 prev 多次求值时传入上次求出的结果, 默认为0 64位整数格式的哈希
std::string qqmusic::utils::get_search_id()
返回随机搜索ID
qqmusic::Result< nlohmann::json > qqmusic::utils::parse_cookie(std::string_view cookie_str)
将Cookie字符串解析成Json对象
key1=value1;key2=value2;key3=value3;key4=value4 | v { "key1":"value1", "key2":"value2", "key3":"value3", "key4":"value4", }
Referenced by qqmusic::utils::CookieJar::CookieJar.
qqmusic::Result< Device > qqmusic::utils::get_device_info()
获取随机设备信息
包含正确结果或异常的Result<Device>
References qqmusic::utils::PathManager::get_cache_path, qqmusic::utils::PathManager::get_instance.
qqmusic::Result< void > qqmusic::utils::cache_device(const Device &device)
将设备信息缓存到文件缓存路径下的device.json
qqmusic::utils::PathManager
References qqmusic::utils::PathManager::get_cache_path, qqmusic::utils::PathManager::get_instance.
boost::asio::awaitable< void > qqmusic::utils::custom_co_spawn_entry_point(boost::asio::awaitable< T, Executor > aw, std::function< void(std::exception_ptr, std::optional< T >)> handler)
Result<>不能进行拷贝, 也没有默认构造函数. boost::asio::co_spawn中会调用默认构造函数. 所以需要包装原本的异步任务, 使用移动构造函数来构造result
aw 异步任务 handler 回调函数 回调函数的签名是void(std::exception_ptr, std::optional<T>), 前一个参数是处理异常的, 后一个参数是正常的返回结果. 如果出错, 则返回结果的std::optional置空 qqmusic::Result
Referenced by qqmusic::utils::AsyncExecutor::async_exec, sync_exec.
T qqmusic::utils::sync_exec(boost::asio::io_context &ioc, qqmusic::Task< T > task)
同步执行异步函数
ioc 当前io_context引用 task 异步任务 返回执行结果 std::runtime_error 当执行出现异常或没有返回预期值
References custom_co_spawn_entry_point.
Referenced by sync_exec.
T qqmusic::utils::sync_exec(qqmusic::Task< T > task)
同步执行异步函数
task 异步任务 返回执行结果
References sync_exec.
qqmusic::Result< qqmusic::utils::QimeiResult > qqmusic::utils::get_qimei(qqmusic::utils::Device &device, std::string_view version)