qqmusic
cover_size
QRLoginType
PhoneLoginEvent
SearchType
AreaType
GenreType
GenderType
IndexType
using qqmusic::Result = typedef Result<T, qqmusic::utils::Exception>
using qqmusic::Task = typedef boost::asio::awaitable<T>
std::string qqmusic::get_album_cover_url(std::string_view mid, cover_size size)
qqmusic::Task< qqmusic::Result< nlohmann::json > > qqmusic::get_album_detail(std::string_view album_mid)
qqmusic::Task< qqmusic::Result< nlohmann::json > > qqmusic::get_album_detail(uint64_t album_id)
qqmusic::Task< qqmusic::Result< nlohmann::json > > qqmusic::get_album_songs(std::string_view album_mid, unsigned int num, unsigned int page)
qqmusic::Task< qqmusic::Result< nlohmann::json > > qqmusic::get_album_songs(uint64_t album_id, unsigned int num, unsigned int page)
qqmusic::Task< qqmusic::Result< QRCode > > qqmusic::get_qrcode(QRLoginType login_type)
qqmusic::Task< qqmusic::Result< QRCodeLoginResult > > qqmusic::check_qq_qr(QRCode &qrc)
qqmusic::Task< qqmusic::Result< QRCodeLoginResult > > qqmusic::check_wx_qr(QRCode &qrc)
qqmusic::Task< qqmusic::Result< PhoneLoginResult > > qqmusic::send_authcode(std::string_view phone, std::string_view country_code)
qqmusic::Task< qqmusic::Result< utils::Credential > > qqmusic::phone_authorize(std::string_view phone, std::string_view auth_code, std::string_view country_code)
Task< Result< Lyric > > qqmusic::get_lyric(std::string_view mid, bool qrc, bool trans, bool roma)
Task< Result< Lyric > > qqmusic::get_lyric(uint64_t id, bool qrc, bool trans, bool roma)
Task< Result< nlohmann::json > > qqmusic::get_mv_detail(std::span< std::string > vids)
Task< Result< std::vector< MvUrl > > > qqmusic::get_mv_urls(std::span< std::string > vids)
Task< Result< nlohmann::json > > qqmusic::hotkey()
Task< Result< nlohmann::json > > qqmusic::keyword_complete(std::string_view keyword)
Task< Result< nlohmann::json > > qqmusic::quick_search(std::string_view keyword)
Task< Result< nlohmann::json > > qqmusic::general_search(std::string_view keyword, unsigned num, unsigned page, bool highlight)
Task< Result< nlohmann::json > > qqmusic::search_by_type(std::string_view keyword, SearchType type, unsigned num_per_page, unsigned page, bool highlight)
Task< Result< nlohmann::json > > qqmusic::get_singer_list(AreaType area=AreaType::ALL, GenderType gender=GenderType::ALL, GenreType genre=GenreType::ALL)
获取符合筛选条件的歌手信息表单
获取JSON格式的歌手信息, 可以使用area, gender和genre筛选 area 区域信息筛选, 默认AreaType::ALL. gender 性别信息筛选, 默认GenderType::ALL. genre 风格信息筛选, 默认GenreType::ALL. 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 AreaType, GenderType, GenreType 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_singer_list_index(AreaType area=AreaType::ALL, GenderType gender=GenderType::ALL, GenreType genre=GenreType::ALL, IndexType index=IndexType::ALL, unsigned sin=0, unsigned cur_page=1)
筛选获得歌曲歌单原始数据
area 区域信息筛选, 默认AreaType::ALL. gender 性别信息筛选, 默认GenderType::ALL. genre 风格信息筛选, 默认GenreType::ALL. sin 跳过的条目数量, 默认0 cur_page 当前页面的索引, 默认1 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 AreaType, GenderType, GenreType, IndexType 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Referenced by get_singer_list_index_all.
Task< Result< nlohmann::json > > qqmusic::get_singer_list_index_all(AreaType area=AreaType::ALL, GenderType gender=GenderType::ALL, GenreType genre=GenreType::ALL, IndexType index=IndexType::ALL)
获取所有符合条件的歌单原始数据
area 区域信息筛选, 默认AreaType::ALL. gender 性别信息筛选, 默认GenderType::ALL. genre 风格信息筛选, 默认GenreType::ALL. index 索引信息筛选, 默认IndexType::ALL. 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 AreaType, GenderType, GenreType, IndexType 异步函数, 返回Task
References qqmusic::utils::AsyncExecutor::get_instance, get_singer_list_index.
Task< Result< nlohmann::json > > qqmusic::get_singer_info(std::string_view mid)
获取歌手基本信息
歌手mid 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_tab_detail(std::string_view mid, TabType type, unsigned page=1, unsigned num=10)
返回标签详细信息
mid 歌手mid type 标签信息 page 页码 num 每页返回数量 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 TabType 异步函数, 返回Task
References qqmusic::TabType::get_id, qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_singer_desc(std::span< std::string > mids, unsigned number=10)
获取多个歌手的简介
mids 歌手mid列表 number 相似歌手数量, 默认为0 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 TabType 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_similar_singers(std::string_view mid, unsigned number=10)
获取相似歌手信息
mids 歌手mid number 相似歌手数量, 默认为0 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 TabType 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_songs_list(std::string_view mid, unsigned num=10, unsigned begin=0)
获取歌手歌曲原始数据
mid 歌手mid num 每次获取的最大数量, 默认10, 最大30 begin 从第几个开始 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Referenced by get_songs_list_all.
Task< Result< nlohmann::json > > qqmusic::get_songs_list_all(std::string_view mid)
获取歌手的所有歌曲
mid 歌手mid 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::AsyncExecutor::get_instance, get_songs_list.
Task< Result< nlohmann::json > > qqmusic::get_album_list(std::string_view mid, unsigned number=10, unsigned begin=0)
获取歌手专辑列表
mid 歌手mid number 单次获取数据量, 默认10 begin 从第几个开始 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Referenced by get_album_list_all.
Task< Result< nlohmann::json > > qqmusic::get_album_list_all(std::string_view mid)
获取歌手所有专辑
mid 歌手mid 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References get_album_list, qqmusic::utils::AsyncExecutor::get_instance.
Task< Result< nlohmann::json > > qqmusic::get_mv_list(std::string_view mid, unsigned number=10, unsigned begin=0)
获取歌手MV列表
mid 歌手mid number 单次获取数据量, 默认10 begin 从第几个开始 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Referenced by get_mv_list_all.
Task< Result< nlohmann::json > > qqmusic::get_mv_list_all(std::string_view mid)
获取歌手所有MV
mid 歌手mid 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::AsyncExecutor::get_instance, get_mv_list.
Task< Result< nlohmann::json > > qqmusic::query_song(std::span< std::string > mids)
批量查询歌曲信息
mids 待查询歌曲mid列表 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::query_song(std::span< uint64_t > ids)
批量查询歌曲信息
mids 待查询歌曲id列表 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< std::vector< SongInfo > > > qqmusic::get_song_urls(std::span< std::string > mids, std::unique_ptr< BaseMediaFileType > file_type=std::make_unique< SongFileType >(), std::optional< utils::Credential > credential=std::nullopt)
批量获取歌曲播放链接
@params mids 歌曲mid列表 @params file_type 歌曲文件类型, 默认MP3_128类型 @params credential 凭证信息 调用示例: std::vector<std::string>mids{"002n5zzy3VVGau"}; //未加密类型 autores=co_awaitget_song_urls(mids, std::make_unique<SongFileType>(SongFileType::ACC_192)); //加密文件类型 autores=co_awaitget_song_urls(mids, std::make_unique<EncryptedSongFileType>(EncryptedSongFileType::MASTER)); 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 BaseMediaFileType, SongFileType, EncryptedSongFileType 异步函数, 返回Task
References qqmusic::utils::AsyncExecutor::get_instance, qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< std::string > > qqmusic::get_try_url(std::string_view mid, std::string_view vs)
获取试听链接
area 区域信息筛选, 默认AreaType::ALL. gender 性别信息筛选, 默认GenderType::ALL. genre 风格信息筛选, 默认GenreType::ALL. 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 AreaType, GenderType, GenreType 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_song_detail(std::string_view mid)
获取歌曲详细信息
mid 歌曲mid 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_song_detail(uint64_t id)
获取歌曲详细信息
id 歌曲id 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_similar_songs(uint64_t songid)
获取相似歌曲列表
id 歌曲id 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_labels(uint64_t songid)
获取歌曲标签信息
id 歌曲id 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_related_songlist(uint64_t songid)
获取相关歌单列表
id 歌曲id 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_related_mv(uint64_t songid, std::optional< std::string > last_mvid=std::nullopt)
获取相关MV
id 歌曲id 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_other_version(std::string_view mid)
获取同名歌曲的其他版本
mid 歌曲mid 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_other_version(uint64_t id)
获取同名歌曲的其他版本
id 歌曲id 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_producer_info(std::string_view mid)
获取歌曲制作者信息
mid 歌曲mid 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 可能返回JSON的null, 即没有制作者信息 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_producer_info(uint64_t id)
获取歌曲制作者信息
id 歌曲id 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 可能返回JSON的null, 即没有制作者信息 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_sheet(std::string_view mid)
获取曲谱信息
mid 歌曲mid 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_fav_num(std::span< uint64_t > id_list, bool readable=true)
获取歌曲的收藏量
id_list 歌曲id列表 readable 是否人类可读 示例: readable==false返回:{'438910555':1000001} readable==true返回:{'438910555':'550w+'} 包含正确JSON格式结果的Task<Result<nlohmann::json>>. 如果产生错误, 返回值包含错误结果和错误类型枚举 异步函数, 返回Task
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_songlist_detail(uint64_t songlist_id, unsigned dirid, unsigned num, unsigned page, bool only_song, bool tag, bool user_info)
Task< Result< nlohmann::json > > qqmusic::get_songlist(uint64_t songlist_id, unsigned dirid)
Task< Result< nlohmann::json > > qqmusic::songlist_create(std::string_view dirname, std::optional< utils::Credential > credential)
Task< Result< bool > > qqmusic::songlist_delete(uint64_t dirid, std::optional< utils::Credential > credential)
Task< Result< bool > > qqmusic::songlist_add_songs(uint64_t dirid, std::span< uint64_t > song_ids, std::optional< utils::Credential > credential)
Task< Result< bool > > qqmusic::songlist_delete_songs(uint64_t dirid, std::span< uint64_t > song_ids, std::optional< utils::Credential > credential)
Task< Result< nlohmann::json > > qqmusic::get_toplist_category()
获取所有排行榜
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< nlohmann::json > > qqmusic::get_toplist_item_detail(unsigned top_id, unsigned num=10, unsigned page=1, bool tag=true)
获取排行榜条目信息
References qqmusic::utils::SessionManager::get_instance, qqmusic::utils::SessionManager::get_session, qqmusic::utils::resp2buf.
Task< Result< std::string > > qqmusic::get_euin(uint64_t musicid)
Task< Result< uint64_t > > qqmusic::get_musicid(std::string_view euin)
Task< Result< nlohmann::json > > qqmusic::get_homepage(std::string_view euin, std::optional< utils::Credential > credential)
Task< Result< nlohmann::json > > qqmusic::get_vip_info(std::optional< utils::Credential > credential)
Task< Result< nlohmann::json > > qqmusic::get_follow_singers(std::string_view euin, unsigned page, unsigned num, std::optional< utils::Credential > credential)
Task< Result< nlohmann::json > > qqmusic::get_fans(std::string_view euin, unsigned page, unsigned num, std::optional< utils::Credential > credential)
Task< Result< nlohmann::json > > qqmusic::get_friend_list(unsigned page, unsigned num, std::optional< utils::Credential > credential)
Task< Result< nlohmann::json > > qqmusic::get_follow_usr(std::string_view euin, unsigned page, unsigned num, std::optional< utils::Credential > credential)
Task< Result< nlohmann::json > > qqmusic::get_created_songlist(uint64_t musicid, std::optional< utils::Credential > credential)
Task< Result< nlohmann::json > > qqmusic::get_fav_song(std::string_view euin, unsigned page, unsigned num, std::optional< utils::Credential > credential)
Task< Result< nlohmann::json > > qqmusic::get_fav_songlist(std::string_view euin, unsigned page, unsigned num, std::optional< utils::Credential > credential)
Task< Result< nlohmann::json > > qqmusic::get_fav_album(std::string_view euin, unsigned page, unsigned num, std::optional< utils::Credential > credential)
Task< Result< nlohmann::json > > qqmusic::get_fav_mv(std::string_view euin, unsigned page, unsigned num, std::optional< utils::Credential > credential)
Task< Result< nlohmann::json > > qqmusic::get_music_gene(std::string_view euin, std::optional< utils::Credential > credential)